# Generated by Django 4.0.4 on 2022-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=144, verbose_name='Текст комментария'),
            preserve_default=False,
        ),
    ]
